<a href="https://www.inove.com.ar"><img src="https://github.com/hernancontigiani/ceia_memorias_especializacion/raw/master/Figures/logoFIUBA.jpg" width="500" align="center"></a>


# Procesamiento de lenguaje natural
## Word2vect


In [1]:
import numpy as np

In [2]:
def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * (np.linalg.norm(b)))

### Datos

In [3]:
corpus = np.array(['que dia es hoy', 'martes el dia de hoy es martes', 'martes muchas gracias'])

### 1 - Obtener el vocabulario del corpus (los términos utilizados)
- Cada documento transformarlo en una lista de términos
- Armar un vector de términos no repetidos de todos los documentos

In [4]:
#creo una lista de palabras para cada documento
doc0= list(corpus[0].split())
print (doc0)


doc1= list(corpus[1].split())
print (doc1)

doc2= list(corpus[2].split())
print (doc2)



['que', 'dia', 'es', 'hoy']
['martes', 'el', 'dia', 'de', 'hoy', 'es', 'martes']
['martes', 'muchas', 'gracias']


In [5]:
#concateno las 3 listas
doc0.extend(doc1)
doc0.extend(doc2)
print (doc0)

['que', 'dia', 'es', 'hoy', 'martes', 'el', 'dia', 'de', 'hoy', 'es', 'martes', 'martes', 'muchas', 'gracias']


In [6]:
#me quedo con los valores unicos luego de la concatenacion
import pandas as pd
vocab_completo=[]
vocab_completo = pd.unique(doc0)

In [7]:
vocab_completo

array(['que', 'dia', 'es', 'hoy', 'martes', 'el', 'de', 'muchas',
       'gracias'], dtype=object)

### 2- OneHot encoding
Data una lista de textos, devolver una matriz con la representación oneHotEncoding de estos

In [8]:
#creo una lista de palabras para cada documento
docu0= list(corpus[0].split())
print (docu0)

docu1= list(corpus[1].split())
print (docu1)

docu2= list(corpus[2].split())
print (docu2)

lst = []

lst.append(docu0)
lst.append(docu1)
lst.append(docu2)
print(lst)

['que', 'dia', 'es', 'hoy']
['martes', 'el', 'dia', 'de', 'hoy', 'es', 'martes']
['martes', 'muchas', 'gracias']
[['que', 'dia', 'es', 'hoy'], ['martes', 'el', 'dia', 'de', 'hoy', 'es', 'martes'], ['martes', 'muchas', 'gracias']]


In [11]:
print(lst)

[['que', 'dia', 'es', 'hoy'], ['martes', 'el', 'dia', 'de', 'hoy', 'es', 'martes'], ['martes', 'muchas', 'gracias']]


In [9]:
oneHotEncoding = np.zeros((len(lst), len(vocab_completo)))

for i, doc in enumerate(lst):
  for j, term in enumerate(vocab_completo):
    oneHotEncoding[i,j] = term in doc

print(oneHotEncoding)

[[1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 1. 1.]]


### 3- Vectores de frecuencia
Data una lista de textos, devolver una matriz con la representación de frecuencia de estos

In [10]:
tf = np.zeros((len(lst), len(vocab_completo)))

for i, doc in enumerate(lst):
  for j, term in enumerate(vocab_completo):
    tf[i,j] = doc.count(term)

print(tf)

[[1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 2. 1. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 1. 1.]]


In [ ]:
vocab_completo = np.sum(lst)
diccionario = {}
for palabra in vocab_completo:
  if palabra in diccionario:
    diccionario[palabra] += 1
  else:
    diccionario[palabra] = 1

for palabra in diccionario:
  frecuencia = diccionario[palabra]
  print(f"La palabra '{palabra}' tiene una frecuencia de {frecuencia}")

La palabra 'que' tiene una frecuencia de 1
La palabra 'dia' tiene una frecuencia de 2
La palabra 'es' tiene una frecuencia de 2
La palabra 'hoy' tiene una frecuencia de 2
La palabra 'martes' tiene una frecuencia de 3
La palabra 'el' tiene una frecuencia de 1
La palabra 'de' tiene una frecuencia de 1
La palabra 'muchas' tiene una frecuencia de 1
La palabra 'gracias' tiene una frecuencia de 1


/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


### 4- TF-IDF
Data una lista de textos, devolver una matriz con la representacion TFIDF

In [14]:
df = oneHotEncoding.sum(axis=0)
n = len(lst)
idf = np.log10(n/df)
tf_idf = (tf * idf).round(decimals=2)
print(tf_idf)

[[0.48 0.18 0.18 0.18 0.   0.   0.   0.   0.  ]
 [0.   0.18 0.18 0.18 0.35 0.48 0.48 0.   0.  ]
 [0.   0.   0.   0.   0.18 0.   0.   0.48 0.48]]


### 5 - Comparación de documentos
Realizar una funcion que reciba el corpus y el índice de un documento y devuelva los documentos ordenados por la similitud coseno

In [18]:
import math
from collections import Counter

def build_vector(iterable1, iterable2):
    counter1 = Counter(iterable1)
    counter2 = Counter(iterable2)
    all_items = set(counter1.keys()).union(set(counter2.keys()))
    vector1 = [counter1[k] for k in all_items]
    vector2 = [counter2[k] for k in all_items]
    return vector1, vector2


def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * (np.linalg.norm(b)))

l1 = "que dia es hoy".split()
l2 = "martes el dia de hoy es martes".split()


a, b = build_vector(l1, l2)
print(cosim(a, b))


#corpus = np.array(['que dia es hoy', 'martes el dia de hoy es martes', 'martes muchas gracias'])

0.5


In [20]:
import math
from collections import Counter

def build_vector(iterable1, iterable2):
    counter1 = Counter(iterable1)
    counter2 = Counter(iterable2)
    all_items = set(counter1.keys()).union(set(counter2.keys()))
    vector1 = [counter1[k] for k in all_items]
    vector2 = [counter2[k] for k in all_items]
    return vector1, vector2


def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * (np.linalg.norm(b)))

l1 = "martes el dia de hoy es martes".split()
l2 = "martes muchas gracias".split()


a, b = build_vector(l1, l2)
print(cosim(a, b))


0.3849001794597505


In [19]:
import math
from collections import Counter

def build_vector(iterable1, iterable2):
    counter1 = Counter(iterable1)
    counter2 = Counter(iterable2)
    all_items = set(counter1.keys()).union(set(counter2.keys()))
    vector1 = [counter1[k] for k in all_items]
    vector2 = [counter2[k] for k in all_items]
    return vector1, vector2


def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * (np.linalg.norm(b)))

l1 = "que dia es hoy".split()
l2 = "martes muchas gracias".split()


a, b = build_vector(l1, l2)
print(cosim(a, b))


0.0
